Fix TODOs
PauloniaAQP/mi_libro_vecino pull request #16
Opened 2022-02-15 15:34 UTC by oscarnar

## Description

TODOs in the project has been fixed. Also, button back in some views has been removed because GoRoutes has some bugs.

Fixes # (issue)

- Issue in pick image for register has been solved.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

# How Has This Been Tested?

All test has been passed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-22 16:49 UTC, ChrisChV approved these changes

2022-03-22 22:52 UTC, juanleondev requested changes

2022-03-22 22:52 UTC, juanleondev commented on lib/ui_utils/functions.dart
> +// import 'dart:html';
```suggestion

```

2022-03-22 22:52 UTC, juanleondev commented on lib/authentication/components/pick_image.dart
> +  Widget _imageIcon(BuildContext context) {
don't use methods for split widgets. Change for statelesswidget

2022-03-23 11:11 UTC, juanleondev approved these changes

2022-03-23 12:41 UTC, merged