QA admin
PauloniaAQP/mi_libro_vecino pull request #33
Opened 2023-02-16 19:05 UTC by oscarnar

## Description

Bugs en el modulo de colaborador. ID: 13, 18, 19, 20

https://paulonia.atlassian.net/jira/software/projects/TOMENTOSA/boards/1?selectedIssue=TOMENTOSA-2778
https://paulonia.atlassian.net/jira/software/projects/TOMENTOSA/boards/1?selectedIssue=TOMENTOSA-2779
https://paulonia.atlassian.net/jira/software/projects/TOMENTOSA/boards/1?selectedIssue=TOMENTOSA-2780
https://paulonia.atlassian.net/jira/software/projects/TOMENTOSA/boards/1?selectedIssue=TOMENTOSA-2781

En resumen:
- El botón de guardar solo debe activarse luego de hacer algún cambio en datos de la información de la biblioteca o del usuario.
- Imagenes dinamicas en las vistas de registro.
- Numero de caracteres del campo de telefono.
- Sincronizacion de textos dinamicos de acuerdo al rol que selecciono el usuario. Esto en las vistas de registro.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

# How Has This Been Tested?

Se corrió los test existentes, y se pasó.

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-16 20:24 UTC, ChrisChV commented
> El botón de guardar solo debe activarse luego de hacer algún cambio en datos de la información de la biblioteca o del usuario.

@oscarnar Si funciona, pero al apretar guardar, debería de volver a desactivarse hasta que el usuario haga otro cambio

2023-02-16 20:39 UTC, ChrisChV commented
> https://paulonia.atlassian.net/jira/software/projects/TOMENTOSA/boards/1?selectedIssue=TOMENTOSA-2779

@oscarnar he probado el probado el registro varias veces y en un caso se me ha quedao cargando infinitamente cuando he llenado todos los campos y las dos imágenes. También me pasó cuando llené todos los campos pero no las imágenes. Notar que en los dos casos moví el mapa para cambiar de ubicación. Derrepente hay algún campo que no se está subiendo bien y genera error

2023-02-16 20:46 UTC, ChrisChV commented
> @oscarnar he probado el probado el registro varias veces y en un caso se me ha quedao cargando infinitamente cuando he llenado todos los campos y las dos imágenes. También me pasó cuando llené todos los campos pero no las imágenes. Notar que en los dos casos moví el mapa para cambiar de ubicación. Derrepente hay algún campo que no se está subiendo bien y genera error

Update: Tal vez tenga que ver con la parte de los tags, pero no estoy seguro, esta medio raro

2023-02-16 20:49 UTC, ChrisChV requested changes
Revisar los comentarios de arriba

2023-02-16 22:15 UTC, oscarnar commented
> Update: Tal vez tenga que ver con la parte de los tags, pero no estoy seguro, esta medio raro

@ChrisChV Me parece que el error surge cuando el usuario se desloguea esto por un stream que escucha los cambios de autenticación y si no encuentra un usuario o librería hace sign out. Es por eso que a veces va bien, y otras no, cuando el proceso de registro va más rápido que el stream de authentication.

2023-02-17 13:22 UTC, ChrisChV commented
@oscarnar Me avisas cuando esté listo para revisar, he visto que has agregado otra tarea a este PR

2023-02-17 13:27 UTC, oscarnar commented
No @ChrisChV son las mismas solo que el ID 22 era similar a otro creo q 18, el problema del registro que a veces funciona y otras no. Porfa revisa el PR

2023-02-17 13:44 UTC, ChrisChV approved these changes

2023-02-17 13:47 UTC, ChrisChV commented
@oscarnar El comentario de este ticket me lleva a este PR, pero no está en el listado de tareas en la descripción, también reviso esa tarea en este PR? https://paulonia.atlassian.net/browse/TOMENTOSA-2783

2023-02-17 13:50 UTC, oscarnar commented
@ChrisChV si porfa revisa ese más, el Big era que en algunos roles se quedaba cargando en el registro

2023-02-17 13:55 UTC, merged