Tomentosa 2844 : Update assets
PauloniaAQP/mi_libro_vecino pull request #38
Opened 2023-02-17 18:13 UTC by heygonzalocaira

## Description

Added the new image in assets 
Fixes MLV | Assets & color updates - TOMENTOSA-2844

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-17 22:41 UTC, ChrisChV requested changes
@heygonzalocaira El asset no ha cambiado en la pantalla de login. Como quedaron con los cambios de colores?

![Captura de pantalla de 2023-02-17 17-39-52](https://user-images.githubusercontent.com/11827305/219811033-a653600c-bb7c-47c7-86e9-1f1d47cf63f5.png)

2023-02-18 00:54 UTC, heygonzalocaira commented
> @heygonzalocaira El asset no ha cambiado en la pantalla de login. Como quedaron con los cambios de colores?
> 
> ![Captura de pantalla de 2023-02-17 17-39-52](https://user-images.githubusercontent.com/11827305/219811033-a653600c-bb7c-47c7-86e9-1f1d47cf63f5.png)

Con respecto a los cambios de colores, pregunte y por el momento se va quedar con el color actual, sin cambiar al otro azul. Sobre la imagen, no comprendo bien cual es el cambio, el figma veo que se usa ese monito. A menos que este entendiendo mal.

2023-02-18 00:55 UTC, heygonzalocaira commented
> > @heygonzalocaira El asset no ha cambiado en la pantalla de login. Como quedaron con los cambios de colores?
> > ![Captura de pantalla de 2023-02-17 17-39-52](https://user-images.githubusercontent.com/11827305/219811033-a653600c-bb7c-47c7-86e9-1f1d47cf63f5.png)
> 
> Con respecto a los cambios de colores, pregunte y por el momento se va quedar con el color actual, sin cambiar al otro azul. Sobre la imagen, no comprendo bien cual es el cambio, el figma veo que se usa ese monito. A menos que este entendiendo mal.
La imagen que estaba en la tarea, tambien era ese monito. Por eso mi duda

2023-02-21 00:59 UTC, ChrisChV approved these changes

2023-02-21 01:00 UTC, merged